### ISSUE TITLE
sidecli setup-node helper

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/sidechain#73]
## Problem

After #72 we will have 4 different files needed to setup a node, this is quite annoying and error prone.

## Suggested solution

Implement

```sh
sidecli setup-node FOLDER_DEST \
  -secret EDSK_SECRET_KEY \
  -uri SELF_URI \
  -tezos_rpc_node TEZOS_NODE_URI \
  -tezos_secret EDSK_SECRET_KEY \
  -tezos_consensus_contract KT1_ADDRESS
```

`Identity.address` **should be derived** from `-secret`.
And Validators.required_confirmation **should be 10**.

**Comment by anchpop** [comment]
What's needed is a command that just creates a [Tezos_interop.Context.t](https://github.com/marigold-dev/sidechain/blob/tezos-interop-context/bin/files.re#L74-L77) and writes it to a file? 

Is that file actually read anywhere yet? If not, is using that file to setup the full pipeline inside the scope of this issue, or does that include #61?

**Comment by EduardoRFS** [comment]
@anchpop creates all the files, look at #72 and on the `files.rei` interface
